package de.dirkgasser.heating;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import static de.dirkgasser.heating.HeatingControl.heatingProgram;
import java.awt.Color;
import java.time.LocalDate;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 * Main Frame for heating control <br>
 * @author Dirk Gasser
 * @version 1.0
 */
public class JFHeatingControl extends javax.swing.JFrame {
    public double tempToBe;
    private NumberFormat numberFormat;
    private HeatDay displayedHeatDay;
    private DateTimeFormatter dtf;
    /**
     * Creates new form JFHeatingControl
     */
    public JFHeatingControl() {
       initComponents();
       this.dispose();
       this.setUndecorated(true);
       dtf = DateTimeFormatter.ofPattern("HH:mm");
       tempToBe = 0;
       numberFormat = NumberFormat.getNumberInstance(Locale.GERMAN);
       ((DecimalFormat) numberFormat).applyPattern("###.#"); 
       heatingProgram.setCurrentDay(LocalDate.now().getDayOfWeek().getValue());
       displayedHeatDay = heatingProgram.getCurrentHeatDay();
       jLday.setText(heatingProgram.getNameOfDay());
       jLHereDefTemp.setText(numberFormat.format(heatingProgram.getDefaultHereTemp()) + " °C ");
       jLAbsentDefTemp.setText(numberFormat.format(heatingProgram.getDefaultAbsentTemp()) + " °C ");
       jLMInDefAbsent.setText(String.valueOf(heatingProgram.getNoMovetoAbsent()));
       jLTolAbsentDef.setText(String.valueOf(heatingProgram.getMoveToBeThereMin()));
       jLHumidityDef.setText(String.valueOf(heatingProgram.getAlarmhumidity()) + " %");
       displayedHeatDay.setStep(0);
       if (displayedHeatDay.getFirstStep() != null) {
            jLstartTime.setText(displayedHeatDay.getFirstStep().getStartTimeAsString());
            jLendTime.setText(displayedHeatDay.getFirstStep().getEndTimeAsString());
            jLTempAbsent.setText(displayedHeatDay.getFirstStep().getAbsenTempAsString());
            jLtempHere.setText(displayedHeatDay.getFirstStep().gethHereTempAsString());
       } else {
           jLstartTime.setText("");
           jLendTime.setText("");
           jLTempAbsent.setText("");
           jLtempHere.setText("");         
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPControl = new javax.swing.JPanel();
        jTtemptobe = new javax.swing.JTextField();
        jTtempIs = new javax.swing.JTextField();
        jThumidity = new javax.swing.JTextField();
        jBreduceTemp = new javax.swing.JButton();
        jBincreaseTemp = new javax.swing.JButton();
        jLtime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPProgram = new javax.swing.JPanel();
        jLday = new javax.swing.JLabel();
        jBprevDay = new javax.swing.JButton();
        jBnextDay = new javax.swing.JButton();
        jLstartTime = new javax.swing.JLabel();
        jLendTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBprevTemp = new javax.swing.JButton();
        jBnextTemp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBreduceTempHere = new javax.swing.JButton();
        jLtempHere = new javax.swing.JLabel();
        jBincreaseTempHere = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBreduceTempAbsent = new javax.swing.JButton();
        jLTempAbsent = new javax.swing.JLabel();
        jBincreaseTempAbsent = new javax.swing.JButton();
        jBnewSelBefore = new javax.swing.JButton();
        jBnewSelAfter = new javax.swing.JButton();
        jBdeleteSel = new javax.swing.JButton();
        jPDefaults = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jBredhereDefTemp = new javax.swing.JButton();
        jLHereDefTemp = new javax.swing.JLabel();
        jLAbsentDefTemp = new javax.swing.JLabel();
        jBredhAbsentDefTemp = new javax.swing.JButton();
        jBincrDefHereTemp = new javax.swing.JButton();
        jBincrDefAbsentTemp = new javax.swing.JButton();
        jBredMInDefAbsent = new javax.swing.JButton();
        jLMInDefAbsent = new javax.swing.JLabel();
        jBincrMInDefAbsent = new javax.swing.JButton();
        jBredTelAbsentDef = new javax.swing.JButton();
        jLTolAbsentDef = new javax.swing.JLabel();
        jBincrTolAbsentDef = new javax.swing.JButton();
        jBredMInDefHum = new javax.swing.JButton();
        jLHumidityDef = new javax.swing.JLabel();
        jBincrMInDefHum = new javax.swing.JButton();
        jBstop = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(480, 320));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPControl.setPreferredSize(new java.awt.Dimension(480, 320));

        jTtemptobe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTtemptobe.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTtemptobe.setText("0 °C");
        jTtemptobe.setAutoscrolls(false);
        jTtemptobe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTtemptobe.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTtemptobe.setEnabled(false);
        jTtemptobe.setPreferredSize(new java.awt.Dimension(150, 35));
        jTtemptobe.setRequestFocusEnabled(false);
        jTtemptobe.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jTtempIs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTtempIs.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTtempIs.setText("0 °C");
        jTtempIs.setAutoscrolls(false);
        jTtempIs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTtempIs.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTtempIs.setEnabled(false);
        jTtempIs.setPreferredSize(new java.awt.Dimension(150, 35));
        jTtempIs.setRequestFocusEnabled(false);

        jThumidity.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jThumidity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jThumidity.setText("50%");
        jThumidity.setAutoscrolls(false);
        jThumidity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jThumidity.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jThumidity.setEnabled(false);
        jThumidity.setPreferredSize(new java.awt.Dimension(150, 35));
        jThumidity.setRequestFocusEnabled(false);
        jThumidity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jThumidityMouseClicked(evt);
            }
        });

        jBreduceTemp.setBackground(new java.awt.Color(51, 102, 255));
        jBreduceTemp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBreduceTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/prev.png"))); // NOI18N
        jBreduceTemp.setMaximumSize(new java.awt.Dimension(43, 43));
        jBreduceTemp.setMinimumSize(new java.awt.Dimension(43, 43));
        jBreduceTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreduceTempActionPerformed(evt);
            }
        });

        jBincreaseTemp.setBackground(new java.awt.Color(255, 51, 51));
        jBincreaseTemp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBincreaseTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/Plusred.png"))); // NOI18N
        jBincreaseTemp.setMaximumSize(new java.awt.Dimension(43, 43));
        jBincreaseTemp.setMinimumSize(new java.awt.Dimension(43, 43));
        jBincreaseTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincreaseTempActionPerformed(evt);
            }
        });

        jLtime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLtime.setText("10:00");
        jLtime.setMaximumSize(new java.awt.Dimension(80, 20));
        jLtime.setMinimumSize(new java.awt.Dimension(80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Soll");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Ist");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Luft");

        javax.swing.GroupLayout jPControlLayout = new javax.swing.GroupLayout(jPControl);
        jPControl.setLayout(jPControlLayout);
        jPControlLayout.setHorizontalGroup(
            jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPControlLayout.createSequentialGroup()
                        .addGroup(jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPControlLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jBreduceTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTtemptobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPControlLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTtempIs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPControlLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jThumidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jBincreaseTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPControlLayout.createSequentialGroup()
                        .addComponent(jLtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(395, Short.MAX_VALUE))))
        );
        jPControlLayout.setVerticalGroup(
            jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPControlLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTtemptobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPControlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBincreaseTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBreduceTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTtempIs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jThumidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Steuerung ", jPControl);

        jLday.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLday.setText("Montag");
        jLday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLday.setMaximumSize(new java.awt.Dimension(120, 30));
        jLday.setMinimumSize(new java.awt.Dimension(120, 30));
        jLday.setPreferredSize(new java.awt.Dimension(180, 30));

        jBprevDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/prev.png"))); // NOI18N
        jBprevDay.setPreferredSize(new java.awt.Dimension(30, 30));
        jBprevDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprevDayActionPerformed(evt);
            }
        });

        jBnextDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/next.png"))); // NOI18N
        jBnextDay.setPreferredSize(new java.awt.Dimension(30, 30));
        jBnextDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnextDayActionPerformed(evt);
            }
        });

        jLstartTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLstartTime.setText("08:00");
        jLstartTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLstartTime.setPreferredSize(new java.awt.Dimension(80, 30));
        jLstartTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLstartTimeMouseClicked(evt);
            }
        });

        jLendTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLendTime.setText("12:00");
        jLendTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLendTime.setPreferredSize(new java.awt.Dimension(80, 30));
        jLendTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLendTimeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("-");

        jBprevTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/prev.png"))); // NOI18N
        jBprevTemp.setPreferredSize(new java.awt.Dimension(30, 30));
        jBprevTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprevTempActionPerformed(evt);
            }
        });

        jBnextTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/next.png"))); // NOI18N
        jBnextTemp.setPreferredSize(new java.awt.Dimension(30, 30));
        jBnextTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnextTempActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Temperatur Anwesend");
        jLabel3.setPreferredSize(new java.awt.Dimension(245, 30));

        jBreduceTempHere.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBreduceTempHere.setText("-");
        jBreduceTempHere.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBreduceTempHere.setIconTextGap(1);
        jBreduceTempHere.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBreduceTempHere.setPreferredSize(new java.awt.Dimension(30, 30));
        jBreduceTempHere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreduceTempHereActionPerformed(evt);
            }
        });

        jLtempHere.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLtempHere.setText("20 °C");
        jLtempHere.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLtempHere.setPreferredSize(new java.awt.Dimension(90, 30));

        jBincreaseTempHere.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBincreaseTempHere.setText("+");
        jBincreaseTempHere.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBincreaseTempHere.setIconTextGap(1);
        jBincreaseTempHere.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBincreaseTempHere.setPreferredSize(new java.awt.Dimension(30, 30));
        jBincreaseTempHere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincreaseTempHereActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Temperatur Abwesend");
        jLabel4.setPreferredSize(new java.awt.Dimension(245, 30));

        jBreduceTempAbsent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBreduceTempAbsent.setText("-");
        jBreduceTempAbsent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBreduceTempAbsent.setIconTextGap(1);
        jBreduceTempAbsent.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBreduceTempAbsent.setPreferredSize(new java.awt.Dimension(30, 30));
        jBreduceTempAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreduceTempAbsentActionPerformed(evt);
            }
        });

        jLTempAbsent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLTempAbsent.setText("20 °C");
        jLTempAbsent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTempAbsent.setPreferredSize(new java.awt.Dimension(90, 30));

        jBincreaseTempAbsent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBincreaseTempAbsent.setText("+");
        jBincreaseTempAbsent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBincreaseTempAbsent.setIconTextGap(1);
        jBincreaseTempAbsent.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBincreaseTempAbsent.setPreferredSize(new java.awt.Dimension(30, 30));
        jBincreaseTempAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincreaseTempAbsentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBreduceTempAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLTempAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jBincreaseTempAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBreduceTempHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLtempHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBincreaseTempHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLtempHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBincreaseTempHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBreduceTempHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBincreaseTempAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTempAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBreduceTempAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jBnewSelBefore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBnewSelBefore.setText("Neu");
        jBnewSelBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnewSelBeforeActionPerformed(evt);
            }
        });

        jBnewSelAfter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBnewSelAfter.setText("Neu");
        jBnewSelAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnewSelAfterActionPerformed(evt);
            }
        });

        jBdeleteSel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBdeleteSel.setText("Löschen");
        jBdeleteSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeleteSelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPProgramLayout = new javax.swing.GroupLayout(jPProgram);
        jPProgram.setLayout(jPProgramLayout);
        jPProgramLayout.setHorizontalGroup(
            jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPProgramLayout.createSequentialGroup()
                .addComponent(jBnewSelBefore)
                .addGap(18, 18, 18)
                .addGroup(jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBprevDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBprevTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPProgramLayout.createSequentialGroup()
                        .addComponent(jLstartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLendTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPProgramLayout.createSequentialGroup()
                        .addComponent(jLday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPProgramLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jBnextDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPProgramLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBnextTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBnewSelAfter)
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProgramLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBdeleteSel)
                .addGap(173, 173, 173))
        );
        jPProgramLayout.setVerticalGroup(
            jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProgramLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPProgramLayout.createSequentialGroup()
                        .addGroup(jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBnewSelAfter)
                            .addGroup(jPProgramLayout.createSequentialGroup()
                                .addGroup(jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBnextDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBprevDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLstartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addComponent(jLendTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBprevTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBnextTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBdeleteSel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPProgramLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jBnewSelBefore)))
                .addContainerGap())
        );

        jTabbedPane1.addTab(" Programm ", jPProgram);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Standardwerte");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Temperatur Anwesend");
        jLabel9.setPreferredSize(new java.awt.Dimension(250, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Temperatur Abwesend");
        jLabel10.setPreferredSize(new java.awt.Dimension(250, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Auf abwesend nach Min.");
        jLabel11.setPreferredSize(new java.awt.Dimension(250, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Toleranz für Abwesend");
        jLabel12.setPreferredSize(new java.awt.Dimension(250, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("Warnung Luftfeuchtigkeit");
        jLabel13.setPreferredSize(new java.awt.Dimension(250, 30));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        jBredhereDefTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/prev.png"))); // NOI18N
        jBredhereDefTemp.setPreferredSize(new java.awt.Dimension(35, 30));
        jBredhereDefTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBredhereDefTempActionPerformed(evt);
            }
        });

        jLHereDefTemp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHereDefTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHereDefTemp.setText("20,5 °C");
        jLHereDefTemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLHereDefTemp.setMinimumSize(new java.awt.Dimension(90, 30));
        jLHereDefTemp.setPreferredSize(new java.awt.Dimension(90, 30));

        jLAbsentDefTemp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLAbsentDefTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAbsentDefTemp.setText("20,5 °C");
        jLAbsentDefTemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLAbsentDefTemp.setPreferredSize(new java.awt.Dimension(90, 30));

        jBredhAbsentDefTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/prev.png"))); // NOI18N
        jBredhAbsentDefTemp.setPreferredSize(new java.awt.Dimension(35, 30));
        jBredhAbsentDefTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBredhAbsentDefTempActionPerformed(evt);
            }
        });

        jBincrDefHereTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/next.png"))); // NOI18N
        jBincrDefHereTemp.setPreferredSize(new java.awt.Dimension(35, 30));
        jBincrDefHereTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincrDefHereTempActionPerformed(evt);
            }
        });

        jBincrDefAbsentTemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/next.png"))); // NOI18N
        jBincrDefAbsentTemp.setPreferredSize(new java.awt.Dimension(35, 30));
        jBincrDefAbsentTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincrDefAbsentTempActionPerformed(evt);
            }
        });

        jBredMInDefAbsent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/prev.png"))); // NOI18N
        jBredMInDefAbsent.setPreferredSize(new java.awt.Dimension(35, 30));
        jBredMInDefAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBredMInDefAbsentActionPerformed(evt);
            }
        });

        jLMInDefAbsent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLMInDefAbsent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMInDefAbsent.setText("5");
        jLMInDefAbsent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLMInDefAbsent.setPreferredSize(new java.awt.Dimension(90, 30));

        jBincrMInDefAbsent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/next.png"))); // NOI18N
        jBincrMInDefAbsent.setPreferredSize(new java.awt.Dimension(35, 30));
        jBincrMInDefAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincrMInDefAbsentActionPerformed(evt);
            }
        });

        jBredTelAbsentDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/prev.png"))); // NOI18N
        jBredTelAbsentDef.setPreferredSize(new java.awt.Dimension(35, 30));
        jBredTelAbsentDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBredTelAbsentDefActionPerformed(evt);
            }
        });

        jLTolAbsentDef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLTolAbsentDef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTolAbsentDef.setText("5");
        jLTolAbsentDef.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTolAbsentDef.setPreferredSize(new java.awt.Dimension(90, 30));

        jBincrTolAbsentDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/next.png"))); // NOI18N
        jBincrTolAbsentDef.setPreferredSize(new java.awt.Dimension(35, 30));
        jBincrTolAbsentDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincrTolAbsentDefActionPerformed(evt);
            }
        });

        jBredMInDefHum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/prev.png"))); // NOI18N
        jBredMInDefHum.setPreferredSize(new java.awt.Dimension(35, 30));
        jBredMInDefHum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBredMInDefHumActionPerformed(evt);
            }
        });

        jLHumidityDef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHumidityDef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHumidityDef.setText("60 %");
        jLHumidityDef.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLHumidityDef.setPreferredSize(new java.awt.Dimension(90, 30));

        jBincrMInDefHum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/dirkgasser/heating/next.png"))); // NOI18N
        jBincrMInDefHum.setPreferredSize(new java.awt.Dimension(35, 30));
        jBincrMInDefHum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincrMInDefHumActionPerformed(evt);
            }
        });

        jBstop.setText("Stop");
        jBstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBstopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDefaultsLayout = new javax.swing.GroupLayout(jPDefaults);
        jPDefaults.setLayout(jPDefaultsLayout);
        jPDefaultsLayout.setHorizontalGroup(
            jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPDefaultsLayout.createSequentialGroup()
                .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPDefaultsLayout.createSequentialGroup()
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBredhereDefTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBredhAbsentDefTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBredMInDefAbsent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBredTelAbsentDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBredMInDefHum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLAbsentDefTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLMInDefAbsent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLTolAbsentDef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLHereDefTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLHumidityDef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBincrDefHereTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBincrDefAbsentTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBincrMInDefAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBincrTolAbsentDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBincrMInDefHum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPDefaultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jBstop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPDefaultsLayout.setVerticalGroup(
            jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDefaultsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDefaultsLayout.createSequentialGroup()
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBredhereDefTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBredhAbsentDefTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBredMInDefAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBredTelAbsentDef, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBredMInDefHum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPDefaultsLayout.createSequentialGroup()
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBincrDefHereTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHereDefTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAbsentDefTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBincrDefAbsentTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLMInDefAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBincrMInDefAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTolAbsentDef, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBincrTolAbsentDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDefaultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLHumidityDef, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBincrMInDefHum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jBstop)
                .addContainerGap())
        );

        jTabbedPane1.addTab(" Einstellungen ", jPDefaults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBreduceTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreduceTempActionPerformed
        tempToBe = Double.parseDouble(jTtemptobe.getText().replaceAll(",", ".").replaceAll("°C", ""));
        tempToBe = tempToBe - 0.5;   
        jTtemptobe.setText(numberFormat.format(tempToBe) + " °C ");
        HeatingControlThread.setManualTemp(tempToBe);
    }//GEN-LAST:event_jBreduceTempActionPerformed

    private void jBincreaseTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincreaseTempActionPerformed
         tempToBe = Double.parseDouble(jTtemptobe.getText().replaceAll(",", ".").replaceAll("°C", ""));
        if (tempToBe < 26) {
            tempToBe = tempToBe + 0.5;   
            jTtemptobe.setText(numberFormat.format(tempToBe) + " °C ");
            HeatingControlThread.setManualTemp(tempToBe);
        }
    }//GEN-LAST:event_jBincreaseTempActionPerformed

    private void jBprevDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprevDayActionPerformed
        // TODO add your handling code here:
        displayedHeatDay = heatingProgram.getprevHeatDay();
        jLday.setText(heatingProgram.getNameOfDay());
        if (displayedHeatDay.getFirstStep() != null) {
            jLstartTime.setText(displayedHeatDay.getFirstStep().getStartTimeAsString());
            jLendTime.setText(displayedHeatDay.getFirstStep().getEndTimeAsString());
            jLTempAbsent.setText(displayedHeatDay.getFirstStep().getAbsenTempAsString());
            jLtempHere.setText(displayedHeatDay.getFirstStep().gethHereTempAsString());
            jLday.setText(heatingProgram.getNameOfDay());
       } else {
           jLstartTime.setText("");
           jLendTime.setText("");
           jLTempAbsent.setText("");
           jLtempHere.setText("");         
       }
    }//GEN-LAST:event_jBprevDayActionPerformed

    private void jBnextDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnextDayActionPerformed
        // TODO add your handling code here:
        displayedHeatDay = heatingProgram.getnextHeatDay();
        jLday.setText(heatingProgram.getNameOfDay());
        if (displayedHeatDay.getFirstStep() != null) {
            jLstartTime.setText(displayedHeatDay.getFirstStep().getStartTimeAsString());
            jLendTime.setText(displayedHeatDay.getFirstStep().getEndTimeAsString());
            jLTempAbsent.setText(displayedHeatDay.getFirstStep().getAbsenTempAsString());
            jLtempHere.setText(displayedHeatDay.getFirstStep().gethHereTempAsString());
            jLday.setText(heatingProgram.getNameOfDay());
       } else {
           jLstartTime.setText("");
           jLendTime.setText("");
           jLTempAbsent.setText("");
           jLtempHere.setText("");         
       }
    }//GEN-LAST:event_jBnextDayActionPerformed

    private void jBnewSelAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnewSelAfterActionPerformed
        // TODO add your handling code here:
        HeatProgramStep newHeatStep;  
        if (displayedHeatDay.getCurrentStep() == null) {
            newHeatStep = new HeatProgramStep(LocalTime.of(0, 0),
                                              LocalTime.of(23,59),      
                                              heatingProgram.getDefaultHereTemp(),
                                              heatingProgram.getDefaultAbsentTemp());
            displayedHeatDay.addHeatStep(newHeatStep);
        } else {
            if (displayedHeatDay.getCurrentStep().getEndTime().isBefore(LocalTime.of(23,59))) {
                if (heatingProgram.getCurrentHeatDay().readNextStep() != null) {
                    if (displayedHeatDay.getCurrentStep().getEndTime().isBefore(heatingProgram.getCurrentHeatDay().readNextStep().getStartTime())) {
                        newHeatStep = new HeatProgramStep(displayedHeatDay.getCurrentStep().getEndTime().plusMinutes(1),
                                              heatingProgram.getCurrentHeatDay().readNextStep().getStartTime().minusMinutes(1),      
                                              heatingProgram.getDefaultHereTemp(),
                                              heatingProgram.getDefaultAbsentTemp());
                        displayedHeatDay.addHeatStep(newHeatStep);
                    } else {
                        JOptionPane.showMessageDialog(this, "Schritt danach grenzt direkt an");
                    }
                } else {
                    newHeatStep = new HeatProgramStep(displayedHeatDay.getCurrentStep().getEndTime().plusMinutes(1),
                                              LocalTime.of(23,59),      
                                              heatingProgram.getDefaultHereTemp(),
                                              heatingProgram.getDefaultAbsentTemp());
                    displayedHeatDay.addHeatStep(newHeatStep);
                }
            }
            
        }
        if (displayedHeatDay.getCurrentStep() != null) {
            jLstartTime.setText(displayedHeatDay.getCurrentStep().getStartTimeAsString());
            jLendTime.setText(displayedHeatDay.getCurrentStep().getEndTimeAsString());
            jLTempAbsent.setText(displayedHeatDay.getCurrentStep().getAbsenTempAsString());
            jLtempHere.setText(displayedHeatDay.getCurrentStep().gethHereTempAsString());
       }
    }//GEN-LAST:event_jBnewSelAfterActionPerformed

    private void jLstartTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLstartTimeMouseClicked
        // TODO add your handling code here:
        LocalTime minTime;
        LocalTime maxTime;
        if (displayedHeatDay.getCurrentStep() == null || displayedHeatDay.getCurrentStep().getStartTime() == null) {
            JOptionPane.showMessageDialog(this, "Zuerst neuen Schritt anlegen");
        } else {
            if (displayedHeatDay.readPrevStep() == null) {
                minTime = LocalTime.of(0, 0); 
            } else {
                minTime = displayedHeatDay.readPrevStep().getEndTime();
            }
            maxTime = displayedHeatDay.getCurrentStep().getEndTime(); 

            final JDTimePopup popupFrame = new JDTimePopup(this, true,displayedHeatDay.getCurrentStep().getStartTime(),
                                                            minTime, maxTime);
            displayedHeatDay.getCurrentStep().setStartTime(popupFrame.getTimeBack());
            jLstartTime.setText(displayedHeatDay.getCurrentStep().getStartTimeAsString());
        }     
    }//GEN-LAST:event_jLstartTimeMouseClicked

    private void jLendTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLendTimeMouseClicked
        // TODO add your handling code here:
        LocalTime minTime;
        LocalTime maxTime;
        if (displayedHeatDay.getCurrentStep() == null || displayedHeatDay.getCurrentStep().getEndTime() == null) {
            JOptionPane.showMessageDialog(this, "Zuerst neuen Schritt anlegen");
        } else {
            minTime = displayedHeatDay.getCurrentStep().getStartTime();
            if (displayedHeatDay.readNextStep() == null) {
                maxTime = LocalTime.of(23, 59); 
            } else {
                maxTime = displayedHeatDay.readNextStep().getStartTime();
            }
            final JDTimePopup popupFrame = new JDTimePopup(this, true,displayedHeatDay.getCurrentStep().getEndTime(),
                                                            minTime, maxTime);
            displayedHeatDay.getCurrentStep().setEndTime(popupFrame.getTimeBack());
            jLendTime.setText(displayedHeatDay.getCurrentStep().getEndTimeAsString());
        }     
    }//GEN-LAST:event_jLendTimeMouseClicked

    private void jBnextTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnextTempActionPerformed
        // TODO add your handling code here:
        if (displayedHeatDay.getNextStep() == null) {
            JOptionPane.showMessageDialog(this, "letzer Schritt");
        } else {
            jLstartTime.setText(displayedHeatDay.getCurrentStep().getStartTimeAsString());
            jLendTime.setText(displayedHeatDay.getCurrentStep().getEndTimeAsString());
            jLTempAbsent.setText(displayedHeatDay.getCurrentStep().getAbsenTempAsString());
            jLtempHere.setText(displayedHeatDay.getCurrentStep().gethHereTempAsString());
        }
    }//GEN-LAST:event_jBnextTempActionPerformed

    private void jBprevTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprevTempActionPerformed
        // TODO add your handling code here:
        if (displayedHeatDay.getPrevStep() == null) {
            JOptionPane.showMessageDialog(this, "erster Schritt");
        } else {
            jLstartTime.setText(displayedHeatDay.getCurrentStep().getStartTimeAsString());
            jLendTime.setText(displayedHeatDay.getCurrentStep().getEndTimeAsString());
            jLTempAbsent.setText(displayedHeatDay.getCurrentStep().getAbsenTempAsString());
            jLtempHere.setText(displayedHeatDay.getCurrentStep().gethHereTempAsString());
        }
    }//GEN-LAST:event_jBprevTempActionPerformed

    private void jBnewSelBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnewSelBeforeActionPerformed
        // TODO add your handling code here:
        HeatProgramStep newHeatStep;  
        if (displayedHeatDay.getCurrentStep() == null) {
            newHeatStep = new HeatProgramStep(LocalTime.of(0, 0),
                                              LocalTime.of(23,59),      
                                              heatingProgram.getDefaultHereTemp(),
                                              heatingProgram.getDefaultAbsentTemp());
            displayedHeatDay.addHeatStep(newHeatStep);
        } else {
            if (displayedHeatDay.getCurrentStep().getStartTime().isAfter(LocalTime.of(0,0))) {
                if (heatingProgram.getCurrentHeatDay().readPrevStep() != null) {
                    if (displayedHeatDay.readPrevStep().getEndTime().plusMinutes(1).isBefore(heatingProgram.getCurrentHeatDay().getCurrentStep().getStartTime())) {
                        newHeatStep = new HeatProgramStep(displayedHeatDay.readPrevStep().getEndTime().plusMinutes(1),
                                              heatingProgram.getCurrentHeatDay().getCurrentStep().getStartTime().minusMinutes(1),      
                                              heatingProgram.getDefaultHereTemp(),
                                              heatingProgram.getDefaultAbsentTemp());
                        displayedHeatDay.addHeatStep(newHeatStep);
                    } else {
                        JOptionPane.showMessageDialog(this, "Schritt davor grenzt direkt an");
                    }
                } else {
                    newHeatStep = new HeatProgramStep(LocalTime.of(0,0),
                                              heatingProgram.getCurrentHeatDay().getCurrentStep().getStartTime().minusMinutes(1),      
                                              heatingProgram.getDefaultHereTemp(),
                                              heatingProgram.getDefaultAbsentTemp());
                    displayedHeatDay.addHeatStep(newHeatStep);
                }
            }
            
        }
        if (displayedHeatDay.getCurrentStep() != null) {
            jLstartTime.setText(displayedHeatDay.getCurrentStep().getStartTimeAsString());
            jLendTime.setText(displayedHeatDay.getCurrentStep().getEndTimeAsString());
            jLTempAbsent.setText(displayedHeatDay.getCurrentStep().getAbsenTempAsString());
            jLtempHere.setText(displayedHeatDay.getCurrentStep().gethHereTempAsString());
       }         
    }//GEN-LAST:event_jBnewSelBeforeActionPerformed

    private void jBdeleteSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeleteSelActionPerformed
        // TODO add your handling code here:
        if (displayedHeatDay.getCurrentStep() != null) {
            displayedHeatDay.removeHeatStep(displayedHeatDay.getCurrentStep());
            if (displayedHeatDay.getCurrentStep() != null) {
                jLstartTime.setText(displayedHeatDay.getCurrentStep().getStartTimeAsString());
                jLendTime.setText(displayedHeatDay.getCurrentStep().getEndTimeAsString());
                jLTempAbsent.setText(displayedHeatDay.getCurrentStep().getAbsenTempAsString());
                jLtempHere.setText(displayedHeatDay.getCurrentStep().gethHereTempAsString());
            } else {
                jLstartTime.setText("");
                jLendTime.setText("");
                jLTempAbsent.setText("");
                jLtempHere.setText("");         
            }
        }
    }//GEN-LAST:event_jBdeleteSelActionPerformed

    private void jBincreaseTempHereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincreaseTempHereActionPerformed
        // TODO add your handling code here:
        if (displayedHeatDay.getCurrentStep() != null) {
            displayedHeatDay.getCurrentStep().increaseHereTemp();
            jLtempHere.setText(displayedHeatDay.getCurrentStep().gethHereTempAsString());
        }
    }//GEN-LAST:event_jBincreaseTempHereActionPerformed

    private void jBreduceTempHereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreduceTempHereActionPerformed
        // TODO add your handling code here:
        if (displayedHeatDay.getCurrentStep() != null) {
            displayedHeatDay.getCurrentStep().decreaseHereTemp();
            jLtempHere.setText(displayedHeatDay.getCurrentStep().gethHereTempAsString());
        }
    }//GEN-LAST:event_jBreduceTempHereActionPerformed

    private void jBincreaseTempAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincreaseTempAbsentActionPerformed
        // TODO add your handling code here:
        if (displayedHeatDay.getCurrentStep() != null) {
            displayedHeatDay.getCurrentStep().increaseAbsentTemp();
            jLTempAbsent.setText(displayedHeatDay.getCurrentStep().getAbsenTempAsString());
        }
    }//GEN-LAST:event_jBincreaseTempAbsentActionPerformed

    private void jBreduceTempAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreduceTempAbsentActionPerformed
        // TODO add your handling code here:
        if (displayedHeatDay.getCurrentStep() != null) {
            displayedHeatDay.getCurrentStep().decreaseAbsentTemp();
            jLTempAbsent.setText(displayedHeatDay.getCurrentStep().getAbsenTempAsString());
        }
    }//GEN-LAST:event_jBreduceTempAbsentActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (heatingProgram != null) {
            heatingProgram.writeHeatProgram("Heating");
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jBredhereDefTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBredhereDefTempActionPerformed
        // TODO add your handling code here:
        heatingProgram.setDefaultHereTemp(heatingProgram.getDefaultHereTemp() - 0.5);  
        jLHereDefTemp.setText(numberFormat.format(heatingProgram.getDefaultHereTemp()) + " °C ");
    }//GEN-LAST:event_jBredhereDefTempActionPerformed

    private void jBincrDefHereTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincrDefHereTempActionPerformed
        // TODO add your handling code here:
        heatingProgram.setDefaultHereTemp(heatingProgram.getDefaultHereTemp() + 0.5);  
        jLHereDefTemp.setText(numberFormat.format(heatingProgram.getDefaultHereTemp()) + " °C ");
    }//GEN-LAST:event_jBincrDefHereTempActionPerformed

    private void jBredhAbsentDefTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBredhAbsentDefTempActionPerformed
        // TODO add your handling code here:
        heatingProgram.setDefaultAbsentTemp(heatingProgram.getDefaultAbsentTemp() - 0.5);  
        jLAbsentDefTemp.setText(numberFormat.format(heatingProgram.getDefaultAbsentTemp()) + " °C ");
    }//GEN-LAST:event_jBredhAbsentDefTempActionPerformed

    private void jBincrDefAbsentTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincrDefAbsentTempActionPerformed
        // TODO add your handling code here:
        heatingProgram.setDefaultAbsentTemp(heatingProgram.getDefaultAbsentTemp() + 0.5);  
        jLAbsentDefTemp.setText(numberFormat.format(heatingProgram.getDefaultAbsentTemp()) + " °C ");
    }//GEN-LAST:event_jBincrDefAbsentTempActionPerformed

    private void jBredMInDefAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBredMInDefAbsentActionPerformed
        // TODO add your handling code here:
        heatingProgram.setNoMovetoAbsent(heatingProgram.getNoMovetoAbsent() - 1);  
        jLMInDefAbsent.setText(String.valueOf(heatingProgram.getNoMovetoAbsent()));
    }//GEN-LAST:event_jBredMInDefAbsentActionPerformed

    private void jBincrMInDefAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincrMInDefAbsentActionPerformed
        // TODO add your handling code here:
        heatingProgram.setNoMovetoAbsent(heatingProgram.getNoMovetoAbsent() + 1);  
        jLMInDefAbsent.setText(String.valueOf(heatingProgram.getNoMovetoAbsent()));
    }//GEN-LAST:event_jBincrMInDefAbsentActionPerformed

    private void jBredTelAbsentDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBredTelAbsentDefActionPerformed
        // TODO add your handling code here:
        heatingProgram.setMoveToBeThereMin(heatingProgram.getMoveToBeThereMin()- 1);  
        jLTolAbsentDef.setText(String.valueOf(heatingProgram.getMoveToBeThereMin()));
    }//GEN-LAST:event_jBredTelAbsentDefActionPerformed

    private void jBincrTolAbsentDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincrTolAbsentDefActionPerformed
        // TODO add your handling code here:
        heatingProgram.setMoveToBeThereMin(heatingProgram.getMoveToBeThereMin()+ 1);  
        jLTolAbsentDef.setText(String.valueOf(heatingProgram.getMoveToBeThereMin()));
    }//GEN-LAST:event_jBincrTolAbsentDefActionPerformed

    private void jBredMInDefHumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBredMInDefHumActionPerformed
        // TODO add your handling code here:
        heatingProgram.setAlarmhumidity(heatingProgram.getAlarmhumidity()- 1);  
        jLHumidityDef.setText(String.valueOf(heatingProgram.getAlarmhumidity()) + " %");
    }//GEN-LAST:event_jBredMInDefHumActionPerformed

    private void jBincrMInDefHumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincrMInDefHumActionPerformed
        // TODO add your handling code here:
        heatingProgram.setAlarmhumidity(heatingProgram.getAlarmhumidity() + 1);  
        jLHumidityDef.setText(String.valueOf(heatingProgram.getAlarmhumidity()) + " %");
    }//GEN-LAST:event_jBincrMInDefHumActionPerformed

    private void jBstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBstopActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "wirklich beenden?", "Ende",YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jBstopActionPerformed

    private void jThumidityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jThumidityMouseClicked
        // TODO add your handling code here:
        HeatingControlThread.setAlarmOff();
    }//GEN-LAST:event_jThumidityMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdeleteSel;
    private javax.swing.JButton jBincrDefAbsentTemp;
    private javax.swing.JButton jBincrDefHereTemp;
    private javax.swing.JButton jBincrMInDefAbsent;
    private javax.swing.JButton jBincrMInDefHum;
    private javax.swing.JButton jBincrTolAbsentDef;
    private javax.swing.JButton jBincreaseTemp;
    private javax.swing.JButton jBincreaseTempAbsent;
    private javax.swing.JButton jBincreaseTempHere;
    private javax.swing.JButton jBnewSelAfter;
    private javax.swing.JButton jBnewSelBefore;
    private javax.swing.JButton jBnextDay;
    private javax.swing.JButton jBnextTemp;
    private javax.swing.JButton jBprevDay;
    private javax.swing.JButton jBprevTemp;
    private javax.swing.JButton jBredMInDefAbsent;
    private javax.swing.JButton jBredMInDefHum;
    private javax.swing.JButton jBredTelAbsentDef;
    private javax.swing.JButton jBredhAbsentDefTemp;
    private javax.swing.JButton jBredhereDefTemp;
    private javax.swing.JButton jBreduceTemp;
    private javax.swing.JButton jBreduceTempAbsent;
    private javax.swing.JButton jBreduceTempHere;
    private javax.swing.JButton jBstop;
    private javax.swing.JLabel jLAbsentDefTemp;
    private javax.swing.JLabel jLHereDefTemp;
    private javax.swing.JLabel jLHumidityDef;
    private javax.swing.JLabel jLMInDefAbsent;
    private javax.swing.JLabel jLTempAbsent;
    private javax.swing.JLabel jLTolAbsentDef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLday;
    private javax.swing.JLabel jLendTime;
    private javax.swing.JLabel jLstartTime;
    private javax.swing.JLabel jLtempHere;
    private javax.swing.JLabel jLtime;
    private javax.swing.JPanel jPControl;
    private javax.swing.JPanel jPDefaults;
    private javax.swing.JPanel jPProgram;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jThumidity;
    private javax.swing.JTextField jTtempIs;
    private javax.swing.JTextField jTtemptobe;
    // End of variables declaration//GEN-END:variables

//manual added code
    public void setTime (LocalTime time) {
        jLtime.setText(time.format(dtf));
    }
    public void setTemp (double temp) {
        jTtempIs.setText(numberFormat.format(temp) + " °C");
    }
    public void setTempToBe (double temp) {
        jTtemptobe.setText(numberFormat.format(temp) + " °C");
    }
     public void setHumidity (double humidity) {
        jThumidity.setText(numberFormat.format(humidity) + " %");
    }
    public void setHeaterSignal(boolean on) {
         if (on == true) {
             jTtemptobe.setBackground(Color.red);
         } else {
             jTtemptobe.setBackground(Color.white); 
         }
    }
    public void setHumiditySignal(boolean on) {
         if (on == true) {
             jThumidity.setBackground(Color.red);
         } else {
             jThumidity.setBackground(Color.white); 
         }
    }
}
